# Permalinks
permalink:           pretty

# Setup
title:               Funny Notebook
tagline:             by jyxk
url:                 http://jyxk.github.io/jyxkBlog
paginate:            1
baseurl:             "https://jyxk.github.io/jyxkBlog"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              jyxk
  url:               https://jyxk.github.io/jyxkBlog
  email:             jyxking007@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jyxk

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
